jobs:
  build:
    docker:
      - image: circleci/node:8.3.0
      
    working_directory: ~/repo

    steps:
      - checkout:
      - run: npm -v
      - run: pwd
      - run: ls -a
      - run: npm install cypress@8.1.0 --save-dev